# Generated by Django 6.0.2 on 2026-04-27 05:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('barangay_clearance', 'Barangay Clearance'), ('residency', 'Certificate of Residency'), ('indigency', 'Certificate of Indigency'), ('business_permit', 'Business Permit'), ('first_time_job_seeker', 'First Time Job Seeker'), ('solo_parent', 'Solo Parent Certificate'), ('senior_citizen', 'Senior Citizen Certificate'), ('pwd', 'PWD Certificate'), ('other', 'Other Certificate')], max_length=50, unique=True)),
                ('template_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('html_template', models.TextField(help_text='HTML template with {{field_name}} placeholders')),
                ('required_fields', models.JSONField(default=dict, help_text='Required fields for this certificate')),
                ('optional_fields', models.JSONField(default=dict, help_text='Optional fields for this certificate')),
                ('template_file', models.FileField(blank=True, help_text='Original template file (Word/PDF) for reference', null=True, upload_to='templates/', validators=[django.core.validators.FileExtensionValidator(['docx', 'pdf'])])),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='CertificateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('date', 'Date'), ('email', 'Email'), ('phone', 'Phone Number'), ('select', 'Dropdown'), ('radio', 'Radio Button')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('choices', models.TextField(blank=True, help_text='For select/radio: comma-separated values')),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='certificates.certificatetemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=300)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_contact', models.CharField(blank=True, max_length=20)),
                ('certificate_data', models.JSONField(default=dict)),
                ('include_signature', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdf/')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='certificates/docx/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('printed', 'Printed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('printed_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_certificates', to=settings.AUTH_USER_MODEL)),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_certificates', to=settings.AUTH_USER_MODEL)),
                ('signature_official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.officialsignature')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificatetemplate')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
