# Generated by Django 6.0.2 on 2026-04-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedcertificate',
            name='pdf_file',
        ),
    ]
