# Generated by Django 6.0.4 on 2026-05-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificatedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='template_type',
            field=models.CharField(choices=[('barangay_clearance', 'Barangay Clearance'), ('residency', 'Certificate of Residency'), ('non-residency', 'Certificate of Non-Residency'), ('Food Assistance', 'Certificate of Food Assistance'), ('indigency', 'Certificate of Indigency'), ('business_permit', 'Business Permit'), ('first_time_job_seeker', 'First Time Job Seeker'), ('solo_parent', 'Solo Parent Certificate'), ('senior_citizen', 'Senior Citizen Certificate'), ('pwd', 'PWD Certificate'), ('other', 'Other Certificate')], max_length=50, unique=True),
        ),
    ]
