# Generated by Django 6.0.4 on 2026-05-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_certificatetemplate_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('date', 'Date'), ('email', 'Email'), ('phone', 'Phone Number'), ('select', 'Dropdown'), ('radio', 'Radio Button'), ('number', 'Number')], max_length=50),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='template_type',
            field=models.CharField(choices=[('barangay_clearance', 'Barangay Clearance'), ('residency', 'Certificate of Residency'), ('non-residency', 'Certificate of Non-Residency'), ('Food_Assistance', 'Certificate of Food Assistance'), ('Financial_Assistance', 'Certificate of Financial Assistance'), ('Program_Certificate', 'Certificate of Program'), ('Participation', 'Certificate of Participation/Conduct of Activity'), ('indigency', 'Certificate of Indigency'), ('animal_ownership', 'Certificate of Ownership (Livestock)'), ('certification', 'BHERT Certification'), ('appearance', 'Certification of Appearance'), ('death_certificate', 'Death Certification'), ('duration', 'Duration Certificate'), ('settlement', 'Amicable Settlement Form'), ('complaint_form', 'Complaint Form'), ('hearing_notice', 'Notice of Hearing'), ('business_permit', 'Business Permit'), ('first_time_job_seeker', 'First Time Job Seeker'), ('solo_parent', 'Solo Parent Certificate'), ('senior_citizen', 'Senior Citizen Certificate'), ('pwd', 'PWD Certificate'), ('other', 'Other Certificate')], max_length=50, unique=True),
        ),
    ]
