# Generated by Django 6.0.4 on 2026-05-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_certificaterequest'),
    ]

    operations = [
        # Use raw SQL to fix the table schema since the existing table has wrong structure
        migrations.RunSQL(
            # Rename columns and add missing ones
            """
            ALTER TABLE certificates_certificaterequest ADD COLUMN recipient_name VARCHAR(300) NOT NULL DEFAULT '';
            ALTER TABLE certificates_certificaterequest ADD COLUMN recipient_email VARCHAR(254) DEFAULT NULL;
            ALTER TABLE certificates_certificaterequest ADD COLUMN recipient_contact VARCHAR(20) DEFAULT NULL;
            """,
            # Reverse operations (for rollback)
            """
            ALTER TABLE certificates_certificaterequest DROP COLUMN recipient_name;
            ALTER TABLE certificates_certificaterequest DROP COLUMN recipient_email;
            ALTER TABLE certificates_certificaterequest DROP COLUMN recipient_contact;
            """
        ),
        migrations.RunSQL(
            # Rename columns using SQLite syntax
            """
            ALTER TABLE certificates_certificaterequest RENAME COLUMN requested_by_id TO requester_id;
            ALTER TABLE certificates_certificaterequest RENAME COLUMN processed_by_id TO reviewed_by_id;
            ALTER TABLE certificates_certificaterequest RENAME COLUMN processed_date TO reviewed_date;
            """,
            # Reverse operations
            """
            ALTER TABLE certificates_certificaterequest RENAME COLUMN requester_id TO requested_by_id;
            ALTER TABLE certificates_certificaterequest RENAME COLUMN reviewed_by_id TO processed_by_id;
            ALTER TABLE certificates_certificaterequest RENAME COLUMN reviewed_date TO processed_date;
            """
        ),
        migrations.RunSQL(
            # Remove notes column and make generated_certificate nullable
            """
            CREATE TABLE certificates_certificaterequest_temp AS SELECT id, requester_id, template_id, recipient_name, recipient_email, recipient_contact, request_data, status, reviewed_by_id, reviewed_date, rejection_reason, generated_certificate_id, created_date, updated_date FROM certificates_certificaterequest;
            DROP TABLE certificates_certificaterequest;
            ALTER TABLE certificates_certificaterequest_temp RENAME TO certificates_certificaterequest;
            """,
            # Reverse operation - recreate with old structure (complex, so we'll leave it)
            """
            -- Reverse would be complex, so not implementing for now
            """
        ),
    ]
