# Generated by Django 6.0.4 on 2026-05-07 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_certificaterequest'),
    ]

    operations = [
        # Drop the existing table with wrong schema
        migrations.RunSQL(
            "DROP TABLE certificates_certificaterequest;",
            # Reverse: recreate table (but we won't implement reverse for simplicity)
            ""
        ),
        # Recreate the table with correct schema
        migrations.RunSQL(
            """
            CREATE TABLE certificates_certificaterequest (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                recipient_name VARCHAR(300) NOT NULL,
                recipient_email VARCHAR(254),
                recipient_contact VARCHAR(20),
                request_data TEXT NOT NULL,
                status VARCHAR(20) NOT NULL,
                reviewed_date DATETIME,
                rejection_reason TEXT,
                created_date DATETIME NOT NULL,
                updated_date DATETIME NOT NULL,
                generated_certificate_id BIGINT UNIQUE,
                requester_id BIGINT NOT NULL REFERENCES accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED,
                reviewed_by_id BIGINT REFERENCES accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED,
                template_id BIGINT NOT NULL REFERENCES certificates_certificatetemplate(id) DEFERRABLE INITIALLY DEFERRED
            );
            CREATE INDEX certificates_certificaterequest_requester_id_idx ON certificates_certificaterequest (requester_id);
            CREATE INDEX certificates_certificaterequest_reviewed_by_id_idx ON certificates_certificaterequest (reviewed_by_id);
            CREATE INDEX certificates_certificaterequest_template_id_idx ON certificates_certificaterequest (template_id);
            CREATE INDEX certificates_certificaterequest_generated_certificate_id_idx ON certificates_certificaterequest (generated_certificate_id);
            """,
            # Reverse operation
            "DROP TABLE certificates_certificaterequest;"
        ),
    ]
