# Generated by Django 6.0.4 on 2026-05-07 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_fix_certificaterequest_schema'),
        ('certificates', '0007_recreate_certificaterequest'),
    ]

    operations = [
    ]
