# Generated by Django 4.2.7 on 2026-05-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('requester', 'Requester - Request Certificates'), ('secretary', 'Secretary - View & Print'), ('officer', 'Officer - View, Print & Edit'), ('admin', 'Admin - Full Access (View, Print, Edit, Delete)')], default='secretary', max_length=20),
        ),
    ]
