# Generated by Django 6.0.2 on 2026-04-27 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('purpose_of_visit', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('accommodated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodated_visits', to=settings.AUTH_USER_MODEL)),
                ('generated_certificates', models.ManyToManyField(blank=True, related_name='visit_transactions', to='certificates.generatedcertificate')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='transactions.visitor')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('certificate_generated', 'Certificate Generated'), ('certificate_printed', 'Certificate Printed'), ('certificate_deleted', 'Certificate Deleted'), ('record_modified', 'Record Modified'), ('record_deleted', 'Record Deleted'), ('history_viewed', 'History Viewed'), ('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('user_permissions_changed', 'User Permissions Changed'), ('template_modified', 'Template Modified'), ('other', 'Other Activity')], max_length=30)),
                ('action_description', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='transaction_timesta_c29d2f_idx'), models.Index(fields=['user', '-timestamp'], name='transaction_user_id_f3f809_idx'), models.Index(fields=['log_type', '-timestamp'], name='transaction_log_typ_4b4e95_idx')],
            },
        ),
    ]
