# Generated by Django 4.2.7 on 2026-05-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='log_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('certificate_generated', 'Certificate Generated'), ('certificate_printed', 'Certificate Printed'), ('certificate_deleted', 'Certificate Deleted'), ('certificate_requested', 'Certificate Requested'), ('record_modified', 'Record Modified'), ('record_deleted', 'Record Deleted'), ('history_viewed', 'History Viewed'), ('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('user_permissions_changed', 'User Permissions Changed'), ('template_modified', 'Template Modified'), ('other', 'Other Activity')], max_length=30),
        ),
    ]
