# Generated by Django 6.0.4 on 2026-05-07 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_fix_certificaterequest_schema'),
        ('transactions', '0002_alter_activitylog_log_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visithistory',
            name='certificate_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to='certificates.certificaterequest'),
        ),
        migrations.AddField(
            model_name='visithistory',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visithistory',
            name='visit_type',
            field=models.CharField(choices=[('walk_in', 'Walk-in Visitor'), ('online_request', 'Online Certificate Request'), ('request_approved', 'Request Approved'), ('certificate_ready', 'Certificate Ready for Pickup'), ('certificate_completed', 'Certificate Completed')], default='walk_in', max_length=25),
        ),
        migrations.AlterField(
            model_name='visithistory',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='transactions.visitor'),
        ),
    ]
